name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/GreptimeTeam/greptimedb-operator
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.4"

      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.0
        with:
          version: v1.50.0
          args: --timeout 10m0s

      - name: Build the project
        run: |
          make

      - name: Create Kubernetes
        run: |
          cat <<EOF | kind create cluster --name runner --config=-
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane
              - role: worker
              - role: worker
          EOF

      - name: Test basic operations of gtctl
        run: |
          cd bin
          ./gtctl create cluster mydb -n default
          ./gtctl get cluster mydb -n default
          ./gtctl get clusters
          ./gtctl delete cluster mydb -n default --tear-down-etcd

      # TODO(zyy17): When the greptimedb is ready, add some SQL tests.
