name: CI

on: [ push, pull_request ]

env:
  GO_VERSION: "1.25"

permissions:
  contents: read

jobs:
  typos-check:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  lint:
    name: Check linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          # '-v' flag is required to show the output of golangci-lint.
          args: -v

  e2e:
    name: End to End tests
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run End to End tests
        run: make e2e
