name: License Checker

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  check-license-header:
    runs-on: ubuntu-latest
    name: check-license-header
    steps:
      - uses: actions/checkout@v2
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
