name: License Checker

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
      - uses: actions/checkout@v4
      - name: Check License Header
        uses: korandoru/hawkeye@v5
