name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build binary
    strategy:
      matrix:
        # The file format is gtctl-<os>-<arch>
        include:
          - os: ubuntu-latest
            file: gtctl-linux-amd64
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            file: gtctl-linux-arm64
            goos: linux
            goarch: arm64
          - os: macos-latest
            file: gtctl-darwin-arm64
            goos: darwin
            goarch: arm64
          - os: macos-latest
            file: gtctl-darwin-amd64
            goos: darwin
            goarch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.4"

      - name: Build project
        run: |
          make
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Calculate checksum and rename binary
        shell: bash
        run: |
          cd bin
          chmod +x gtctl
          tar -zcvf ${{ matrix.file }}.tgz gtctl
          echo $(shasum -a 256 ${{ matrix.file }}.tgz | cut -f1 -d' ') > ${{ matrix.file }}.sha256sum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file }}
          path: bin/${{ matrix.file }}.tgz

      - name: Upload checksum of artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file }}.sha256sum
          path: bin/${{ matrix.file }}.sha256sum

  release:
    name: Release artifacts
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.ref_name }}"
          files: |
            **/gtctl-*
